spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432}/${DB_NAME:otusnss}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  sql:
    init:
      mode: always
  main:
    allow-circular-references: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
      show-sql: true
logging:
  level:
    ROOT: INFO