spring:
  main:
    allow-circular-references: true
  batch:
    jdbc:
      initialize-schema: "always"
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  mongodb:
    embedded:
      version: 3.4.0

  data:
    mongodb:
      host: localhost
      port: 27017
      database: user_db
  sql:
    init:
      mode: always
    main:
      allow-circular-references: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
      show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432}/${DB_NAME:otusnss}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  h2:
    console:
      enabled: true
      path: /h2-console

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.example.springbatch.chandgelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

app:
  ages-count-to-add: 1
  input-file: entries.csv
  output-file: output.dat

#debug: true
